services:
  unbound:
    container_name:
      unbound
    image: klutchell/unbound:${UNBOUND_IMAGE}
    network_mode: host
    volumes:
      - ./unbound/custom.conf.d:/etc/unbound/custom.conf.d:ro
    restart: unless-stopped