services:
  pihole:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_IMAGE}
    network_mode: host
    environment:
      TZ: ${TZ:-Europe/London}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'LOCAL'
      FTLCONF_dns_upstreams: '127.0.0.1#5335'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
      - unbound