services:
  samba:
    image: dockurr/samba:${SAMBA_IMAGE}
    container_name: samba
    ports:
      - "445:445"
    volumes:
      - /mnt/storage/:/storage
      - ./samba/users.conf:/etc/samba/users.conf:ro
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
    restart: unless-stopped